services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb-notification
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-notification
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5

  notification-service:
    build: .
    container_name: notification-service
    ports:
      - "8083:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:password@mongodb:27017/notification-service?authSource=admin
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongodb-data:
  rabbitmq-data: